version: '3'

services:
  node:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./app:/usr/app
    depends_on:
      - db
    networks:
      - api
    healthcheck:
      test: ["CMD-SHELL", "node -e 'require(\"http\").createServer((req, res) => { res.end(); }).listen(3000)'"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: fullcyclepassword
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - api

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - node
      - db
    networks:
      - api
      
networks:
  api: {}
