version: '3'

services:
  node:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - /usr/src/app/
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api
    

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: fullcyclepassword
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - api

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - node
      - db
    networks:
      - api
      
networks:
  api: {}
